### ISSUE TITLE
Using `vue-toastr`

### ISSUE THREAD

**Issue by mubaidr** [Deveodk/vue-error-tracker#3]
Hi! This plug-in is is easy to setup and works well. I have question about compatibility between `vue-toastr` and this plug-in. 

Can I use the original fork of `@deveodk/vue-toastr` (https://github.com/s4l1h/vue-toastr) with this plugin or is there some breaking API difference?

**Comment by jasonkellydk** [comment]
Thank you for the kind words. The package is made to work with our own toastr package, this is due to the usage of prototypes instead of calling the methods directly from root. You can find the correct toastr package here ``` @deveodk/vue-toastr ``` (https://github.com/Deveodk/vue-toastr). But you can always write your own driver and just require it in the ```vue.use()```section
